export const data = {
  cardsArts: [
    {
      id: 1,
      nftType: "arts",
      prevImg: "card-2.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-2.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 2,
      nftType: "sports",
      prevImg: "card-1.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-1.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 3,
      nftType: "videos",
      prevImg: "card-3.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-3.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 4,
      nftType: "arts",
      prevImg: "card-4.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-4.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 5,
      nftType: "sports",
      prevImg: "card-5.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-5.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 6,
      nftType: "arts",
      prevImg: "card-6.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-6.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 7,
      nftType: "videos",
      prevImg: "card-7.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-7.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 8,
      nftType: "videos",
      prevImg: "card-8.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-8.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 9,
      nftType: "sports",
      prevImg: "card-9.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-9.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 10,
      nftType: "sports",
      prevImg: "card-10.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-1.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 11,
      nftType: "arts",
      prevImg: "card-11.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-2.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 12,
      nftType: "sports",
      prevImg: "card-12.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-3.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 13,
      nftType: "arts",
      prevImg: "card-13.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-4.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 14,
      nftType: "videos",
      prevImg: "card-14.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-5.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 15,
      nftType: "videos",
      prevImg: "card-15.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-6.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 16,
      nftType: "sports",
      prevImg: "card-16.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-7.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
    {
      id: 17,
      nftType: "sports",
      prevImg: "card-17.png",
      title: "lorem ipsum dolor sit amet",
      creatorImg: "person-8.png",
      creatorName: "salvador dali",
      currentPaid: "4.89",
    },
  ],
  cardsArtists: [
    {
      id: 1,
      prevImg: "art-1.png",
      artistImg: "artist-1.png",
      artistName: "crypto punks",
      artistPrice: "12.7",
    },
    {
      id: 2,
      prevImg: "art-2.png",
      artistImg: "artist-2.png",
      artistName: "doodles",
      artistPrice: "18.9",
    },
    {
      id: 3,
      prevImg: "art-3.png",
      artistImg: "artist-3.png",
      artistName: "bored ape yacht",
      artistPrice: "27.3",
    },
    {
      id: 4,
      prevImg: "art-4.png",
      artistImg: "artist-4.png",
      artistName: "capsule house",
      artistPrice: "15.4",
    },
    {
      id: 5,
      prevImg: "art-2.png",
      artistImg: "artist-3.png",
      artistName: "dafenshi",
      artistPrice: "21.1",
    },
  ],
};
